
####测试数据库
mongodbHost: 127.0.0.1
mongodbPort: 27017
mongodbUsername: root
mongodbPassword: xiaoyi
mongodbDatabase: blog

###redis配置
redisPort: 6379
redisHost: 120.78.88.123
redisPassword: af666

spring:
   data:
     mongodb:
       uri: mongodb://${mongodbUsername}:${mongodbPassword}@${mongodbHost}:${mongodbPort}/${mongodbDatabase}
   redis:
   # Redis数据库索引（默认为0）
     database: 1
     host: ${redisHost}
     port: ${redisPort}
     password: ${redisPassword}
     pool:
       # 连接池最大连接数（使用负值表示没有限制）
       max-active: 8
       # 连接池最大阻塞等待时间（使用负值表示没有限制）
       max-wait: -1
       # 连接池中的最大空闲连接
       max-idle: 8
       # 连接池中的最小空闲连接
       min-idle: 0
       # 连接超时时间（毫秒）
     timeout: 5000





